import { SupabaseProvider } from "@/contexts/SupabaseContext";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Spindox Pictionary",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={` antialiased bg-gray-950 text-white`}>
        <SupabaseProvider>{children}</SupabaseProvider>
      </body>
    </html>
  );
}
